//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('HealthMetrics')
export class HealthMetricsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  metricId: number;

  @Column('integer', { nullable: true })
  customerId: number;

  @Column('text', { nullable: true })
  type: string;

  @Column('real', { nullable: true })
  value: number;

  @Column('text', { nullable: true })
  unit: string;

  @Column('date', { nullable: true })
  date: Date;
}
